#!/bin/bash

# Declarations
testsRoot="./test-html"
HOST="localhost"
PORT=8085
ADDRESS="http://$HOST:$PORT"
TITLE_FORMAT="\n\n==================== %s ====================\n"
SUBTITLE_FORMAT="\n---------- %s ----------\n"

function isTestPassed()
{
      eval "$1"
      if [ $? -eq 0 ]; then
          echo "✅ Test passed: $1"
          return 1;
      else
          echo "❌ Test failed: $1"
          return 0;
      fi
}

# Script execution
if ! lsof -i:${PORT} > /dev/null 2>&1; then
    echo "❌ webserv is not listening to port ${PORT}, try again."
    exit 1
fi

# Give rights to tests CGI scripts to be executed
chmod -R 777 test-html/cgi-bin

# HTTP ERRORS
HOST_HEADER="Host: localhost"

printf "$TITLE_FORMAT" "HTTP ERRORS"

printf "${SUBTITLE_FORMAT}" "HTTP CODE 200"
cmd="curl --silent --include '$ADDRESS' | grep -qi 'HTTP/1.1 200'"
isTestPassed "${cmd}"

printf "${SUBTITLE_FORMAT}" "HTTP CODE 400"
cmd="(echo -e 'GET / HTTP/1.1\r\n$HOST_HEADER\r\nContent-type::\r\n\r\n'; sleep 1) \
| nc -q 1 localhost 8085 | grep -qi 'HTTP/1.1 400'"
isTestPassed "${cmd}"

cmd="(echo -e '\r\n$HOST_HEADER\r\n\r\n'; sleep 1) \
| nc -q 1 localhost 8085 | grep -qi 'HTTP/1.1 400'"
isTestPassed "${cmd}"

cmd="(echo -e 'GET / HTTP/1.1 \r\n$HOST_HEADER\r\n\r\n'; sleep 1) \
| nc -q 1 localhost 8085 | grep -qi 'HTTP/1.1 400'"
isTestPassed "${cmd}"

cmd="(echo -e 'GET / HTTP/1.1\r\n$HOST_HEADER\r\nConnection: keep-alive\r\nKeep-Alive: timeout=TEST\r\n\r\n'; sleep 1) \
| nc localhost 8085 | grep -qi 'HTTP/1.1 400'"
isTestPassed "${cmd}"

printf "${SUBTITLE_FORMAT}" "HTTP CODE 403"
test403Forbidden="resources/test-403-forbidden.html"
chmod 000 "$testsRoot/$test403Forbidden"
cmd="curl --silent --include '$ADDRESS/$test403Forbidden' | grep -qi 'HTTP/1.1 403'"
isTestPassed "${cmd}"
chmod 664 "$testsRoot/$test403Forbidden"

printf "${SUBTITLE_FORMAT}" "HTTP CODE 404"
cmd="curl --silent --include '$ADDRESS/notexist' | grep -qi 'HTTP/1.1 404'"
isTestPassed "${cmd}"

printf "${SUBTITLE_FORMAT}" "HTTP CODE 405"
cmd="curl --silent --include -X PUT $ADDRESS | grep -qi 'HTTP/1.1 405'"
isTestPassed "${cmd}"

printf "${SUBTITLE_FORMAT}" "HTTP CODE 408"
cmd="curl --silent --include -X POST '$ADDRESS/cgi-bin/py/infinite_loop.py' | grep -qi 'HTTP/1.1 408'"
isTestPassed "${cmd}"

test413Limit="resources/test-413-limit.html"
printf "${SUBTITLE_FORMAT}" "HTTP CODE 413: POST with 1025 bytes"
# Limit = 1k, Body = 1024 characters (nginx source code)
cmd="curl --silent --include -X POST -H 'Content-Type: text/plain' \
--data 'ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE' \
'$ADDRESS/$test413Limit' | grep -qi 'HTTP/1.1 413'"
isTestPassed "${cmd}"

printf "${SUBTITLE_FORMAT}" "HTTP CODE 200: POST with 1024 bytes"
# Limit = 1k, Body = 1024 characters (nginx source code)
cmd="curl --silent --include -X POST -H 'Content-Type: text/plain' \
--data 'ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCD' \
'$ADDRESS/$test413Limit' | grep -qi 'HTTP/1.1 200'"
isTestPassed "${cmd}"